const citiesInIsrael = [
    "Umm Al-Fahm",
    "Ofakim",
    "Or Yehuda",
    "Or Akiva",
    "Eilat",
    "Elad",
    "Ariel",
    "Ashdod",
    "Ashkelon",
    "Baqa Al-Gharbiya",
    "Be'er Sheva",
    "Beit Shean",
    "Beit Shemesh",
    "Beit Arieh",
    "Bnei Brak",
    "Bat Yam",
    "Givat Shmuel",
    "Givatayim",
    "Dimona",
    "Hod Hasharon",
    "Herzliya",
    "Hadera",
    "Holon",
    "Haifa",
    "Tiberias",
    "Tayibe",
    "Tira",
    "Tirat Carmel",
    "Tamra",
    "Yavne",
    "Yehud-Monosson",
    "Yokneam Illit",
    "Jerusalem",
    "Kfar Yona",
    "Kfar Saba",
    "Kfar Qassem",
    "Karmiel",
    "Lod",
    "Migdal Haemek",
    "Modiin-Maccabim-Reut",
    "Modiin Illit",
    "Ma'ale Adumim",
    "Maaleh Oren",
    "Nahariya",
    "Nof Hagalil",
    "Ness Ziona",
    "Nazareth",
    "Nesher",
    "Netivot",
    "Netanya",
    "Sakhneen",
    "Acre",
    "Afula",
    "Arava",
    "Arad",
    "Petah Tikva",
    "Safed",
    "Qalansawe",
    "Kiryat Ono",
    "Kiryat Ata",
    "Kiryat Bialik",
    "Kiryat Gat",
    "Kiryat Yam",
    "Kiryat Motzkin",
    "Kiryat Malakhi",
    "Kiryat Shmona",
    "Rosh Haayin",
    "Rishon Lezion",
    "Rahat",
    "Rehovot",
    "Ramla",
    "Ramat Gan",
    "Ramat Hasharon",
    "Raanana",
    "Sderot",
    "Shfaram",
    "Tel Aviv",
];
  
export default citiesInIsrael;
